/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElConfigProvider: (typeof import("element-plus/es"))["ElConfigProvider"];
    ElDialog: (typeof import("element-plus/es"))["ElDialog"];
    ReDialog: (typeof import("./src/components/ReDialog/index.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    Src: (typeof import("./src/components/ReImageVerify/src/index.vue"))["default"];
  }
}
