/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from "vue";

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExportDialog: typeof import('./../src/components/ImportExport/ExportDialog.vue')['default']
    ImportDialog: typeof import('./../src/components/ImportExport/ImportDialog.vue')['default']
    ReDialog: typeof import('./../src/components/ReDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../src/components/ReIcon/src/Select.vue')['default']
    Src: typeof import('./../src/components/ReImageVerify/src/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const ElAvatar: (typeof import("element-plus/es"))["ElAvatar"];
  const ElBacktop: (typeof import("element-plus/es"))["ElBacktop"];
  const ElBadge: (typeof import("element-plus/es"))["ElBadge"];
  const ElBreadcrumb: (typeof import("element-plus/es"))["ElBreadcrumb"];
  const ElBreadcrumbItem: (typeof import("element-plus/es"))["ElBreadcrumbItem"];
  const ElButton: (typeof import("element-plus/es"))["ElButton"];
  const ElButtonGroup: (typeof import("element-plus/es"))["ElButtonGroup"];
  const ElCard: (typeof import("element-plus/es"))["ElCard"];
  const ElCheckbox: (typeof import("element-plus/es"))["ElCheckbox"];
  const ElCol: (typeof import("element-plus/es"))["ElCol"];
  const ElConfigProvider: (typeof import("element-plus/es"))["ElConfigProvider"];
  const ElDialog: (typeof import("element-plus/es"))["ElDialog"];
  const ElDivider: (typeof import("element-plus/es"))["ElDivider"];
  const ElDropdown: (typeof import("element-plus/es"))["ElDropdown"];
  const ElDropdownItem: (typeof import("element-plus/es"))["ElDropdownItem"];
  const ElDropdownMenu: (typeof import("element-plus/es"))["ElDropdownMenu"];
  const ElEmpty: (typeof import("element-plus/es"))["ElEmpty"];
  const ElForm: (typeof import("element-plus/es"))["ElForm"];
  const ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
  const ElIcon: (typeof import("element-plus/es"))["ElIcon"];
  const ElInput: (typeof import("element-plus/es"))["ElInput"];
  const ElInputNumber: (typeof import("element-plus/es"))["ElInputNumber"];
  const ElMenu: (typeof import("element-plus/es"))["ElMenu"];
  const ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
  const ElRow: (typeof import("element-plus/es"))["ElRow"];
  const ElScrollbar: (typeof import("element-plus/es"))["ElScrollbar"];
  const ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
  const ElSwitch: (typeof import("element-plus/es"))["ElSwitch"];
  const ElTable: (typeof import("element-plus/es"))["ElTable"];
  const ElTableColumn: (typeof import("element-plus/es"))["ElTableColumn"];
  const ElTabPane: (typeof import("element-plus/es"))["ElTabPane"];
  const ElTabs: (typeof import("element-plus/es"))["ElTabs"];
  const ElTag: (typeof import("element-plus/es"))["ElTag"];
  const ElText: (typeof import("element-plus/es"))["ElText"];
  const ElTooltip: (typeof import("element-plus/es"))["ElTooltip"];
  const ExportDialog: (typeof import("./../src/components/ImportExport/ExportDialog.vue"))["default"];
  const ImportDialog: (typeof import("./../src/components/ImportExport/ImportDialog.vue"))["default"];
  const ReDialog: (typeof import("./../src/components/ReDialog/index.vue"))["default"];
  const RouterLink: (typeof import("vue-router"))["RouterLink"];
  const RouterView: (typeof import("vue-router"))["RouterView"];
  const Select: (typeof import("./../src/components/ReIcon/src/Select.vue"))["default"];
  const Src: (typeof import("./../src/components/ReImageVerify/src/index.vue"))["default"];
}
